const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',

    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',

    //admin
    FETCH_GENDER_START: 'FETCH_GENDER_START',
    FETCH_GENDER_SUCCESS: 'FETCH_GENDER_SUCCESS',
    FETCH_GENDER_FAIL: 'FETCH_GENDER_FAIL',

    FETCH_ROLE_SUCCESS: 'FETCH_ROLE_SUCCESS',
    FETCH_ROLE_FAIL: 'FETCH_ROLE_FAIL',

    FETCH_GENRE_START: 'FETCH_GENRE_START',
    FETCH_GENRE_SUCCESS: 'FETCH_GENRE_SUCCESS',
    FETCH_GENRE_FAIL: 'FETCH_GENRE_FAIL',

    FETCH_SHOW_SUCCESS: 'FETCH_SHOW_SUCCESS',
    FETCH_SHOW_FAIL: 'FETCH_SHOW_FAIL',

    FETCH_ALLCODE_BOOKING_TIME_SUCCESS: 'FETCH_ALLCODE_BOOKING_TIME_SUCCESS',
    FETCH_ALLCODE_BOOKING_TIME_FAIL: 'FETCH_ALLCODE_BOOKING_TIME_FAIL',
    //lay tat nguoi dung va tao nguoi dung
    CREATE_USER_SUCESS: 'CREATE_USER_SUCESS',
    CREATE_USER_FAIL: 'CREATE_USER_FAIL',

    FETCH_ALL_USERS_SUCCESS: 'FETCH_ALL_USERS_SUCCESS',
    FETCH_ALL_USERS_FAIL: 'FETCH_ALL_USERS_FAIL',

    FETCH_MY_USERS_SUCCESS: 'FETCH_MY_USERS_SUCCESS',
    FETCH_MY_USERS_FAIL: 'FETCH_MY_USERS_FAIL',

    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAIL: 'DELETE_USER_FAIL',

    EDIT_USER_SUCESS: 'EDIT_USER_SUCESS',
    EDIT_USER_FAIL: 'EDIT_USER_FAIL',

    EDIT_MY_USER_SUCESS: 'EDIT_MY_USER_SUCESS',
    EDIT_MY_USER_FAIL: 'EDIT_MY_USER_FAIL',
    //lay tat ca phim va tao phim
    CREATE_FILM_SUCESS: 'CREATE_FILM_SUCESS',
    CREATE_FILM_FAIL: 'CREATE_FILM_FAIL',

    DELETE_FILM_SUCCESS: 'DELETE_FILM_SUCCESS',
    DELETE_FILM_FAIL: 'DELETE_FILM_FAIL',

    EDIT_FILM_SUCESS: 'EDIT_FILM_SUCESS',
    EDIT_FILM_FAIL: 'EDIT_FILM_FAIL',

    FETCH_TOP_FILMS_SUCCESS: 'FETCH_TOP_FILMS_SUCCESS',
    FETCH_TOP_FILMS_FAIL: 'FETCH_TOP_FILMS_FAIL',

    FETCH_ALL_FILMS_SUCCESS: 'FETCH_ALL_FILMS_SUCCESS',
    FETCH_ALL_FILMS_FAIL: 'FETCH_ALL_FILMS_FAIL',

    FETCH_NOW_SHOWING_FILMS_SUCCESS: 'FETCH_NOW_SHOWING_FILMS_SUCCESS',
    FETCH_NOW_SHOWING_FILMS_FAIL: 'FETCH_NOW_SHOWING_FILMS_FAIL',

    FETCH_COMING_SOON_SUCCESS: 'FETCH_COMING_SOON_SUCCESS',
    FETCH_COMING_SOON_FAIL: 'FETCH_COMING_SOON_FAIL',

    SAVE_INFOR_FILM_SUCESS: 'SAVE_INFOR_FILM_SUCESS',
    SAVE_INFOR_FILM_FAIL: 'SAVE_INFOR_FILM_FAIL',

    SAVE_BANNER_FILM_SUCESS: 'SAVE_BANNER_FILM_SUCESS',
    SAVE_BANNER_FILM_FAIL: 'SAVE_BANNER_FILM_FAIL',

    FETCH_BANNER_FILMS_SUCCESS: 'FETCH_BANNER_FILMS_SUCCESS',
    FETCH_BANNER_FILMS_FAIL: 'FETCH_BANNER_FILMS_FAIL',
    //NEWS
    CREATE_NEWS_SUCESS: 'CREATE_NEWS_SUCESS',
    CREATE_NEWS_FAIL: 'CREATE_NEWS_FAIL',

    FETCH_ALL_NEWS_SUCCESS: 'FETCH_ALL_NEWS_SUCCESS',
    FETCH_ALL_NEWS_FAIL: 'FETCH_ALL_NEWS_FAIL',

    DELETE_NEWS_SUCCESS: 'DELETE_NEWS_SUCCESS',
    DELETE_NEWS_FAIL: 'DELETE_NEWS_FAIL',

    EDIT_NEWS_SUCESS: 'EDIT_NEWS_SUCESS',
    EDIT_NEWS_FAIL: 'EDIT_NEWS_FAIL',

    FETCH_TOP_NEWS_SUCCESS: 'FETCH_TOP_NEWS_SUCCESS',
    FETCH_TOP_NEWS_FAIL: 'FETCH_TOP_NEWS_FAIL',
    //CONTACT US
    FETCH_ALL_CONTACT_US_SUCCESS: 'FETCH_ALL_CONTACT_US_SUCCESS',
    FETCH_ALL_CONTACT_US_FAIL: 'FETCH_ALL_CONTACT_US_FAIL',

    CREATE_CONTACT_US_SUCCESS: 'CREATE_CONTACT_US_SUCCESS',
    CREATE_CONTACT_US_FAIL: 'CREATE_CONTACT_US_FAIL',
    //CINEMA-TECH
    CREATE_CINEMA_TECH_SUCESS: 'CREATE_CINEMA_TECH_SUCESS',
    CREATE_CINEMA_TECH_FAIL: 'CREATE_CINEMA_TECH_FAIL',

    FETCH_ALL_CINEMA_TECHS_SUCCESS: 'FETCH_ALL_CINEMA_TECHS_SUCCESS',
    FETCH_ALL_CINEMA_TECHS_FAIL: 'FETCH_ALL_CINEMA_TECHS_FAIL',

    DELETE_CINEMA_TECH_SUCCESS: 'DELETE_CINEMA_TECH_SUCCESS',
    DELETE_CINEMA_TECH_FAIL: 'DELETE_CINEMA_TECH_FAIL',

    EDIT_CINEMA_TECH_SUCESS: 'EDIT_CINEMA_TECH_SUCESS',
    EDIT_CINEMA_TECH_FAIL: 'EDIT_CINEMA_TECH_FAIL',
    //SEAT
    FETCH_SEAT_SUCCESS: 'FETCH_SEAT_SUCCESS',
    FETCH_SEAT_FAIL: 'FETCH_SEAT_FAIL',
    //PRICE
    FETCH_PRICE_SUCCESS: 'FETCH_PRICE_SUCCESS',
    FETCH_PRICE_FAIL: 'FETCH_PRICE_FAIL',
    //SEAT_TYPE
    FETCH_SEAT_TYPE_SUCCESS: 'FETCH_SEAT_TYPE_SUCCESS',
    FETCH_SEAT_TYPE_FAIL: 'FETCH_SEAT_TYPE_FAIL',
    //PAYMENT_TYPE
    FETCH_PAYMENT_TYPE_SUCCESS: 'FETCH_PAYMENT_TYPE_SUCCESS',
    FETCH_PAYMENT_TYPE_FAIL: 'FETCH_PAYMENT_TYPE_FAIL',

    CREATE_PAYMENT_TYPE_SUCESS: 'CREATE_PAYMENT_TYPE_SUCESS',
    CREATE_PAYMENT_TYPE_FAIL: 'CREATE_PAYMENT_TYPE_FAIL',
    //BUY-COMBO
    CREATE_BUY_COMBO_SUCESS: 'CREATE_BUY_COMBO_SUCESS',
    CREATE_BUY_COMBO_FAIL: 'CREATE_BUY_COMBO_FAIL',

    FETCH_ALL_BUY_COMBOS_SUCCESS: 'FETCH_ALL_BUY_COMBOS_SUCCESS',
    FETCH_ALL_BUY_COMBOS_FAIL: 'FETCH_ALL_BUY_COMBOS_FAIL',

    DELETE_BUY_COMBO_SUCCESS: 'DELETE_BUY_COMBO_SUCCESS',
    DELETE_BUY_COMBO_FAIL: 'DELETE_BUY_COMBO_FAIL',

    EDIT_BUY_COMBO_SUCESS: 'EDIT_BUY_COMBO_SUCESS',
    EDIT_BUY_COMBO_FAIL: 'EDIT_BUY_COMBO_FAIL',
    //BOOKING
    CREATE_BOOKING_SUCESS: 'CREATE_BOOKING_SUCESS',
    CREATE_BOOKING_FAIL: 'CREATE_BOOKING_FAIL',

})

export default actionTypes;